const express = require('express')
const router = express.Router()
const messageHandler = require('../router_handle/message')

// 公告消息路由。
router.post('/publishMessage', messageHandler.publishMessage)
router.post('/companyMessageList', messageHandler.companyMessageList)
router.post('/systemMessageList', messageHandler.systemMessageList)
router.post('/editMessage', messageHandler.editMessage)
router.post('/searchMessageBydepartment', messageHandler.searchMessageBydepartment)
router.post('/searchMessageByLevel', messageHandler.searchMessageByLevel)
router.post('/getMessage', messageHandler.getMessage)
router.post('/updateClick', messageHandler.updateClick)
router.post('/firstDelete', messageHandler.firstDelete)
router.post('/recycleList', messageHandler.recycleList)
router.post('/getRecycleMessageLength', messageHandler.getRecycleMessageLength)
router.post('/returnRecycleListData', messageHandler.returnRecycleListData)
router.post('/recover', messageHandler.recover)
router.post('/deleteMessage', messageHandler.deleteMessage)
router.post('/getCompanyMessageLength', messageHandler.getCompanyMessageLength)
router.post('/getSystemMessageLength', messageHandler.getSystemMessageLength)
router.post('/returnCompanyListData', messageHandler.returnCompanyListData)
router.post('/returnSystemListData', messageHandler.returnSystemListData)

module.exports = router
