const express = require('express')
const router = express.Router()
const productHandler = require('../router_handle/product')

// 产品库存与出库路由。
router.post('/createProduct', productHandler.createProduct)
router.post('/deleteProduct', productHandler.deleteProduct)
router.post('/editProduct', productHandler.editProduct)
router.post('/getProductList', productHandler.getProductList)
router.post('/applyOutProduct', productHandler.applyOutProduct)
router.post('/applyProductList', productHandler.applyProductList)
router.post('/withdrawApplyProduct', productHandler.withdrawApplyProduct)
router.post('/auditProduct', productHandler.auditProduct)
router.post('/searchProductForId', productHandler.searchProductForId)
router.post('/searchProductForApplyId', productHandler.searchProductForApplyId)
router.post('/searchProductForOutId', productHandler.searchProductForOutId)
router.post('/getProductLength', productHandler.getProductLength)
router.post('/getApplyProductLength', productHandler.getApplyProductLength)
router.post('/auditProductList', productHandler.auditProductList)
router.post('/getOutProductLength', productHandler.getOutProductLength)
router.post('/returnProductListData', productHandler.returnProductListData)
router.post('/returnApplyProductListData', productHandler.returnApplyProductListData)
router.post('/returnOutProductListData', productHandler.returnOutProductListData)

module.exports = router
